services:
  gin-db: 
    container_name: mysql-gin
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3312:3306
    volumes:
      - mysql-gin:/var/lib/mysql
    networks:
      - app-network

  adminer-gs:
    container_name: adminer-gin
    image: adminer
    restart: unless-stopped
    ports:
      - 7080:8080
    networks:
      - app-network

volumes:
  mysql-gin:

networks:
  app-network:  